/*
 * GENERATED AUTOMATICALLY DO NOT FIX
 * 2018-06-14 13:20:16
 */

#ifndef CMD_H
#define CMD_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum cmd_e {
	CMD_MIN = 0,
	CMD_POST_CONTROL_REBOOT = 1,
	CMD_POST_CONTROL_RESURFACE = 2,
	CMD_POST_CONTROL_SELF_TEST = 3,
	CMD_POST_FIRMWARE_BURN = 4,
	CMD_GET_FIRMWARE_SHA1 = 5,
	CMD_GET_RTC = 6,
	CMD_POST_RTC = 7,
	CMD_PUT_ANTENNA_DEFECTIVE_COLUMNS = 8,
	CMD_GET_ANTENNA_DEFECTIVE_COLUMNS = 9,
	CMD_PUT_ENV_PARAMS = 10,
	CMD_GET_ENV_PARAMS = 11,
	CMD_PATCH_ACTIVE_SCHEDULE = 12,
	CMD_PUT_ACTIVE_SCHEDULE = 13,
	CMD_GET_ACTIVE_SCHEDULE = 14,
	CMD_PATCH_UTCS_TRANSMIT_SCHEDULE = 15,
	CMD_PUT_UTCS_TRANSMIT_SCHEDULE = 16,
	CMD_GET_UTCS_TRANSMIT_SCHEDULE = 17,
	CMD_PATCH_SATCOM_SCHEDULE = 18,
	CMD_PUT_SATCOM_SCHEDULE = 19,
	CMD_GET_SATCOM_SCHEDULE = 20,
	CMD_PUT_PASSIVE_PROCESSING_PARAMETERS = 21,
	CMD_PATCH_PASSIVE_PROCESSING_PARAMETERS = 22,
	CMD_GET_PASSIVE_PROCESSING_PARAMETERS = 23,
	CMD_POST_ATT_1 = 24,
	CMD_GET_ATT_1 = 25,
	CMD_DELETE_ATT_1 = 26,
	CMD_GET_PASSIVE_MARKS = 27,
	CMD_GET_ACTIVE_GET_ANGLE_ID_MARKS = 28,
	CMD_GET_UTCS_INBOX = 29,
	CMD_GET_PASSIVE_TARGETS = 30,
	CMD_GET_ACTIVE_TARGETS = 31,
	CMD_PATCH_STREAMS = 32,
	CMD_PUT_STREAMS = 33,
	CMD_GET_STREAMS = 34,
	CMD_GET_SELF_DIAGNOSIS = 35,
	CMD_POST_DO_MEASUREMENTS = 36,
	CMD_POST_CONTROL_SET_MODE = 37,
	CMD_SERVICE = 38,
	CMD_STREAM1 = 39,
	CMD_STREAM2 = 40,
	CMD_STREAM3 = 41,
	CMD_STREAM4 = 42,
	CMD_STREAM5 = 43,
	CMD_STREAM6 = 44,
	CMD_STREAM7 = 45,
	CMD_STREAM8 = 46,
	CMD_STREAM9 = 47,
	CMD_STREAM10 = 48,
	CMD_STREAM11 = 49,
	CMD_STREAM12 = 50,
	CMD_STREAM13 = 51,
	CMD_STREAM14 = 52,
	CMD_STREAM15 = 53,
	CMD_STREAM16 = 54,
	CMD_STREAM17 = 55,
	CMD_STREAM18 = 56,
	CMD_STREAM19 = 57,
	CMD_STREAM20 = 58,
	CMD_STREAM21 = 59,
	CMD_STREAM22 = 60,
	CMD_MAX = 61
} cmd_e;

#ifdef __cplusplus
}
#endif


#endif

